[supabase]
url = "https://vkvwxnnirqtkwfhuskvo.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZrdnd4bm5pcnF0a3dmaHVza3ZvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzMDAzMTcsImV4cCI6MjA3MTg3NjMxN30.-yAV2mYDcesXM5wncmbcq1GlpD60q32lx6pe1bPDKfg"
